openapi: 3.0.0
info:
  title: lab3 api
  version: 1.0.0
paths:
  /items:
    get:
      summary: Get all items
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: 
                - id: 1
                  value: "Item 1"
                - id: 2
                  value: "Item 2"

    post:
      summary: Add a new item
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
              required:
                - value
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Item successfully added to the database"

  /items/{id}:
    put:
      summary: Update an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the item to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
              required:
                - value
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Item successfully updated"

    delete:
      summary: Delete an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the item to delete
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Item successfully deleted"
